### ISSUE TITLE
getSeconds sometimes returns different values

### ISSUE THREAD

**Issue by SarcevicAntonio** [kwhitley/itty-time#2]
I noticed some weird behavior when trying out getSeconds in an Advent of Vue challenge (that I did in Svelte) and had to replace it sadly.

Sometimes getSeconds('1 day') and the others return weird values. 

<img width="1178" alt="Screenshot 2022-12-04 at 00 53 00" src="https://user-images.githubusercontent.com/6685200/205467204-7394a6a1-48d6-4e12-b82d-00648b359eaf.png">

Here is a minimal repro that showcases it with a flickering number and in the console when using chrome 107.0.5304.121: https://svelte.dev/repl/31907b32e50042d8b8f068148de739a3?version=3.53.1

EDIT: same on firefox 107.0 (lol they share version numbers atm?) and safari 16.1

**Comment by kwhitley** [comment]
Should be resolved in `0.2.1` :)

## The Problem
Internally, itty-time was using the build-in Date functions for manipulating time from a fixed date.  This meant using things like `setHours` and `setMonth` and such.  `getSeconds` was actually a derivative function of `datePlus`, which needed those bits.  Regardless, some of these functions return inconsistent results, which is especially irritating when you're asking for a very easily calculation like seconds, days, etc.

## The Solution
I've reworked itty-time to make `getSeconds` the first-class citizen, and default to using basic time math for all "obvious" units (seconds, minutes, hours, days, weeks), and only use the built-ins for months and years (where you don't want to add a fixed number of seconds, you typically want to move the month/year).  The new solution should be faster in most cases (simple multiplication is faster than getters/setters), and only added 11 bytes total, as much of the specific unit translation to use all the setters could be removed.  Furthermore, with `getSeconds` now not dependent on the other functions, the import for that alone should actually be smaller!

## Notes
I've verified it in your demo code (that was super helpful btw!), and confirmed the value remains 86400 now :)
